// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myfinance_aspnetcore_infra;

#nullable disable

namespace _4_myfinance_aspnetcore_infra.Migrations
{
    [DbContext(typeof(MyFinanceDbContext))]
    partial class MyFinanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("myfinance_aspnetcore_domain.Entities.PlanoConta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlanoConta");
                });

            modelBuilder.Entity("myfinance_aspnetcore_domain.Entities.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Historico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanoContaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlanoContaId");

                    b.ToTable("Transacao");
                });

            modelBuilder.Entity("myfinance_aspnetcore_domain.Entities.Transacao", b =>
                {
                    b.HasOne("myfinance_aspnetcore_domain.Entities.PlanoConta", "PlanoConta")
                        .WithMany()
                        .HasForeignKey("PlanoContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanoConta");
                });
#pragma warning restore 612, 618
        }
    }
}
